version: '3.8'

services:

  backend:
    build: ./services/backend
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:root@db:5432/database
      - TZ=Europe/Moscow
    volumes:
      - ./services/backend:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`dev.localhost`)"
    restart: always

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database
      - TZ=Europe/Moscow
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  traefik:
    image: traefik:v2.9.6
    ports:
      - 8000:80
      - 8001:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data: