"""add part_id to OrderParts table

Revision ID: 6db44337c4bf
Revises: 916a4bc7438a
Create Date: 2024-02-05 19:09:47.959964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db44337c4bf'
down_revision: Union[str, None] = '916a4bc7438a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_parts', sa.Column('part_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_parts', 'parts', ['part_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_parts', type_='foreignkey')
    op.drop_column('order_parts', 'part_id')
    # ### end Alembic commands ###
