"""set null supplier_id

Revision ID: a98a295ca7fd
Revises: 81290e54b155
Create Date: 2024-02-06 06:03:53.282958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98a295ca7fd'
down_revision: Union[str, None] = '81290e54b155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parts_supplier_id_fkey', 'parts', type_='foreignkey')
    op.create_foreign_key(None, 'parts', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.create_foreign_key('parts_supplier_id_fkey', 'parts', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
