"""Sales and Part

Revision ID: f8e4b845656a
Revises: eb581707ba68
Create Date: 2024-02-13 00:07:02.597112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e4b845656a'
down_revision: Union[str, None] = 'eb581707ba68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('name', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'count')
    op.drop_column('sales', 'phone')
    op.drop_column('sales', 'name')
    op.drop_column('parts', 'sale_price')
    # ### end Alembic commands ###
